[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "s3-put-object-trigger"
path = "src/cmd/s3-put-object-trigger.rs"

[dependencies]
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
lambda_runtime = "0.7"
aws_lambda_events = "0.7"