[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "transcribe"
path = "src/cmd/transcribe.rs"

[dependencies]
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
lambda_runtime = "0.7"
aws_lambda_events = "0.7"
aws-config = "0.51"
aws-sdk-transcribe = "0.21"
aws-sdk-dynamodb = "0.21"
chrono = "0.4"
uuid = { version = "1", features = ["serde", "v4"] }
dotenv = "0.15"
url-escape = "0.1"