[package]
name = "lambda"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "transcribe"
path = "src/cmd/transcribe.rs"

[[bin]]
name = "transcribe_post_process"
path = "src/cmd/transcribe_post_process.rs"

[[bin]]
name = "subtitle"
path = "src/cmd/subtitle.rs"

[dependencies]
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
itertools = "0.10"
lambda_runtime = "0.7"
aws_lambda_events = "0.7"
aws-config = "0.51"
aws-sdk-s3 = "0.21"
aws-sdk-transcribe = "0.21"
aws-sdk-translate = "0.21"
aws-sdk-dynamodb = "0.21"
aws-sdk-sqs = "0.21"
aws-sdk-sns = "0.21"
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+0_21"] }
chrono = "0.4"
uuid = { version = "1", features = ["serde", "v4"] }
dotenv = "0.15"
url-escape = "0.1"