POST https://video-search.drskur.xyz/api/video/subtitle
Content-Type: application/json
Authorization: Basic ZHJza3VyOg==

{
  "video_id": "fc247815-94f3-40d7-8cd2-f80007a04c14",
  "target_lang": "en"
}

###

GET https://video-search.drskur.xyz/api/video/search?q=사과&lang=ko
Content-Type: application/json
Authorization: Basic ZHJza3VyOg==

###
GET http://localhost:3000/api/video/search?q=두부&lang=ko&video_id=fc247815-94f3-40d7-8cd2-f80007a04c14
Content-Type: application/json
Authorization: Basic ZHJza3VyOg==