POST https://umbkrb0eng.execute-api.us-east-1.amazonaws.com/api/video/subtitle
Content-Type: application/json
Authorization: Basic ZHJza3VyOg==

{
  "video_id": "b7392c01-c218-461d-bcf5-725f85ee1b33",
  "target_lang": "en"
}

###
