[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"
anyhow = "1"
env_logger = "0.9"
actix-web = "4.2"
lambda-web = { version = "0.2", features = ["actix4"] }
aws-sdk-dynamodb = "0.21"
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+0_21"] }
aws-config = "0.51"
dotenv = "0.15"
askama = "0.11"

[build-dependencies]
askama = "0.11"