[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"
env_logger = "0.9"
actix-web = "4.2"
lambda-web = { version = "0.2", features = ["actix4"] }
dotenv = "0.15"
tantivy = "0.18"
lindera-tantivy = { version = "0.18", features = ["ko-dic"] }